name: TranscribeAndSummarizeAudioAndVideo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=25.0
  - ffmpeg
  - numpy==2.0.1
  - pandas==2.2.3
  - pip:
    - openai==1.3.8
    - python-dotenv==1.0.0
    - streamlit==1.28.1
    - pydub==0.25.1
    - ffmpeg-python==0.2.0
    - fpdf2==2.7.6
    - markdown2==2.4.10
    - requests==2.31.0
    - ollama==0.1.7